;; -*- mode: eask; lexical-binding: t -*-

(package "ejn"
         "1.0.0"
         "EJN (Emacs Jupyter Notebook)")

(website-url "https://github.com/Kyohei-Prj/emacs-jupyter-notebook")
(keywords "jupyter" "python")

(package-file "ejn.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(development
 (depends-on "ellsp"))

(depends-on "emacs" "30.2")
